### ISSUE TITLE
New Design for T-Task

### ISSUE THREAD

**Issue by ghost** [teobaranga/T-Tasks#2]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a beautiful icon.

Best Regards.

*I've already designed one.*

![ttask](https://user-images.githubusercontent.com/36993664/39834034-745f6ad2-53d4-11e8-911d-fbfbd208e844.jpg)

**Comment by teobaranga** [comment]
Hi @Yasujizr,
Thank you very much for the design and I appreciate you finding my app interesting enough to design a logo for it! I gotta say it's a pretty clever icon. This is however an app that's still in its early stages, so nothing is set in stone - even the name. For that reason, I don't think that an icon based on the app name is the best idea. That being said, I'm open to featuring your design in the readme as an alternative icon, if you're interested. Cheers!

**Comment by Yasujizr** [comment]
Thank you @teobaranga ,
If you want, we can design a logo separately from the beginning. If you want, we can use it for now. This is entirely up to you, the offer is nice to me but your wish is more important. I am waiting for your reply.

**Comment by teobaranga** [comment]
Then I'm afraid I'm not interested in having a new logo. I spent a lot of time designing and making the current one. I'm still a fan of it and I don't see any reason to have a new one at the moment.

**Comment by Yasujizr** [comment]
It is all right, thank you for your honest answer. You can still add it to "readme" file, if you want. Good luck for the app, you do a great job. 

Best regards.
